# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  variables:
    - group: 'diiga-djt-dev-secrets-vg'
    - group: 'diiga-djt-dev-parameters-vg'
  jobs:  
  - job: Build
    displayName: Build SSD
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo "The PWD is ${PWD}"
          echo "the system.defaultworkingdirecotry is ${SYSTEM_DEFAULTWORKINGDIRECTORY}"
          echo "The AHDBURL is ${AHDBURL}"
          echo "The CLIENT is ${CLIENT}"
          echo "The DBURL is ${DBURL}"
          echo "The PLUGINDBURL is ${PLUGINDBURL}"
          echo "The SPTARGET is ${SPTARGET}"
          ESCAPEDSRCDIR=$(/bin/sed 's/[&/\]/\\&/g' <<<"$SYSTEM_DEFAULTWORKINGDIRECTORY")
          echo $ESCAPEDSRCDIR
          echo "${DIIGA-DJT-DEV-IIQDAT}" > ./iiq.dat.txt
          echo "${DIIGA-DJT-DEV-IIQCFG}" > ./iiq.cfg.txt
          echo "${DIIGA-DJT-DEV-IIQDBUSER-SECRET}" > ./iiqdbusersecret.txt
          echo "${DIIGA-DJT-DEV-SPADMIN-SECRET}" > ./spadminsecret.txt
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.txt'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
