# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  variables:
    - group: 'diiga-djt-dev-secrets-vg'
    - group: 'diiga-djt-dev-parameters-vg'
  jobs:  
  - job: Build
    displayName: Build SSD
    steps:
    - bash: |
        # Write your commands here
        echo "The PWD is ${PWD}"
        echo "the system.defaultworkingdirecotry is ${SYSTEM_DEFAULTWORKINGDIRECTORY}"
        echo "The AHDBURL is ${AHDBURL}"
        echo "The CLIENT is ${CLIENT}"
        echo "The DBURL is ${DBURL}"
        echo "The PLUGINDBURL is ${PLUGINDBURL}"
        echo "The SPTARGET is ${SPTARGET}"
        echo "The dat secret is $IIQDATSECRET" 
        echo "The cfg secret is $IIQCFGSECRET" 
        echo "The dbuser secret is $DBUSERSECRET" 
        echo "the spadmin secret is $SPADMINSECRET"
        ESCAPEDSRCDIR=$(/bin/sed 's/[&/\]/\\&/g' <<<"$SYSTEM_DEFAULTWORKINGDIRECTORY")
        echo $ESCAPEDSRCDIR
        echo "$IIQDATSECRET" | base64 --decode > ./iiq.dat.jks
        echo "$IIQCFGSECRET" > ./iiq.cfg.txt
        echo "$DBUSERSECRET" > ./iiqdbusersecret.txt
        echo "$SPADMINSECRET" > ./spadminsecret.txt
      displayName: Running bash Script
      env:
        IIQDATSECRET: $(diiga-djt-dev-iiqdat)
        IIQCFGSECRET: $(diiga-djt-dev-iiqcfg)
        DBUSERSECRET: $(diiga-djt-dev-iiqdbuser-secret)
        SPADMINSECRET: $(diiga-djt-dev-spadmin-secret)
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.txt'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
